"""Backing-pointer registry (Workstream C4; domain anchor §8D.44).

Every ConceptNode carries an opaque ``backing_pointer`` (a string
handle). At runtime, callers resolve the handle through this registry
to the actual implementation (callable, accessor, SLM invocation,
pretty-printer, etc.). The opacity is intentional (§8D.44): the
DB-ontology navigation walks ConceptNode records, not python
implementations.

Two surfaces:

  * **Registration**: ``register(handle, callable)`` binds a runtime
    handle to an implementation. Handles are typically generated by
    the materialiser that creates the ConceptNode (e.g.,
    ``compiled_from_scans::searchable_url::<concept_id>``).
  * **Resolution**: ``resolve(handle)`` returns the bound callable,
    or ``None`` if the handle is unknown.
  * **Invocation**: ``invoke(handle, **kwargs)`` is the canonical
    call site; returns the implementation's output.

Built-in resolvers handle the common backing-pointer prefixes:

  * ``compiled_from_scans::searchable_url::<id>`` →
        the search-and-paginate routine for that URL.
  * ``compiled_from_scans::detected_accessor::<id>`` →
        xpath-read accessor that pulls the field from a DOM snapshot.
  * ``compiled_from_scans::xpath_pattern::<id>`` →
        the pattern-matcher that returns matching xpaths.
  * ``module::<dotted.path>`` → imported python attribute.
  * ``db::cypher`` → Database cypher executor.
  * ``db::tfidf_retrieve`` → TF-IDF retrieval.
  * ``slm::invoke`` → on-device SLM call.
  * ``pretty_print::default`` → JSON pretty-printer for chunk data.

Anything not handled falls through to ``None`` and the agent's
emitter layer counts the action as "received but not invoked"
(see ``ActionResolver``).
"""

from __future__ import annotations

import importlib
import json
import logging
import threading
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

class BackingRegistry:
    """Opaque-handle → callable registry (§8D.44)."""

    def __init__(self):
        self._bindings: Dict[str, Callable[..., Any]] = {}
        # Fix: cache prefix-resolved callables so frequent invokes
        # (e.g. the agent's hot-path invoke action firing dozens of
        # times per tick) don't pay the resolver-walk + closure-
        # construction overhead per call. The cache is invalidated
        # by ``register`` and ``unregister`` for safety.
        self._prefix_cache: Dict[str, Callable[..., Any]] = {}
        # Open/closed extensibility — external modules call
        # ``register_prefix_resolver(prefix, factory)`` to add their
        # own backing-pointer kinds without editing the registry. The
        # list is consulted AFTER the built-in resolvers so user
        # extensions can't accidentally shadow core handles unless they
        # use a more-specific prefix.
        self._extra_prefix_resolvers: List[tuple] = []   # [(prefix, factory)]
        self._lock = threading.Lock()
        # Register built-in resolvers so the common backing pointers
        # work without explicit registration calls.
        self._register_builtins()

    def register(self, handle: str, fn: Callable[..., Any]) -> None:
        """Bind a handle to an implementation. Last-write-wins."""
        with self._lock:
            self._bindings[handle] = fn
            # Explicit binding overrides cached prefix resolution.
            self._prefix_cache.pop(handle, None)

    def unregister(self, handle: str) -> bool:
        with self._lock:
            self._prefix_cache.pop(handle, None)
            return self._bindings.pop(handle, None) is not None

    def register_prefix_resolver(
        self,
        prefix: str,
        factory: Callable[[str], Optional[Callable[..., Any]]],
    ) -> None:
        """Open/closed extension hook (§8D.44).

        ``prefix`` — a handle prefix the factory will handle (e.g.
            ``"vendor::"``).
        ``factory(handle: str) -> Optional[callable]`` — given a handle
            matching the prefix, return the invocable for it (or
            ``None`` to decline).

        Extensions live alongside built-ins; built-ins still win when
        a more-specific prefix matches (e.g. ``compiled_from_scans::``
        always resolves through core code, never an extension that
        registered ``compiled_from_scans::custom::``). Registering an
        identical prefix twice replaces the prior factory.

        The runtime stays open to new backing-pointer kinds (new scan
        types, third-party SLM providers, sandboxed user code) without
        editing this file.
        """
        if not prefix:
            return
        with self._lock:
            self._extra_prefix_resolvers = [
                (p, f) for (p, f) in self._extra_prefix_resolvers
                if p != prefix
            ]
            self._extra_prefix_resolvers.append((prefix, factory))
            # Bust the prefix cache so previously-failed resolutions
            # under this prefix get a second chance.
            self._prefix_cache = {
                h: fn for h, fn in self._prefix_cache.items()
                if not h.startswith(prefix)
            }

    def unregister_prefix_resolver(self, prefix: str) -> bool:
        with self._lock:
            before = len(self._extra_prefix_resolvers)
            self._extra_prefix_resolvers = [
                (p, f) for (p, f) in self._extra_prefix_resolvers
                if p != prefix
            ]
            self._prefix_cache = {
                h: fn for h, fn in self._prefix_cache.items()
                if not h.startswith(prefix)
            }
            return len(self._extra_prefix_resolvers) < before

    def resolve(self, handle: str) -> Optional[Callable[..., Any]]:
        """Return the bound callable, or fall through to a prefix resolver."""
        with self._lock:
            fn = self._bindings.get(handle)
            if fn is not None:
                return fn
            cached = self._prefix_cache.get(handle)
            if cached is not None:
                return cached
        resolved = self._resolve_by_prefix(handle)
        if resolved is not None:
            with self._lock:
                self._prefix_cache[handle] = resolved
                # Bound cache size so unbounded handle vocabularies
                # (e.g. one per concept node) don't accumulate.
                if len(self._prefix_cache) > 1024:
                    # Drop the oldest 25% via insertion-order pop.
                    for k in list(self._prefix_cache.keys())[: 256]:
                        self._prefix_cache.pop(k, None)
        return resolved

    def invoke(self, handle: str, **kwargs: Any) -> Dict[str, Any]:
        """Resolve + call. Returns ``{ ok, result?, error? }``."""
        fn = self.resolve(handle)
        if fn is None:
            return {"ok": False, "error": f"no binding for handle: {handle}"}
        try:
            out = fn(**kwargs)
            return {"ok": True, "result": out}
        except Exception as e:
            return {"ok": False, "error": f"{type(e).__name__}: {e}"}

    # -------------------------------------------------------------------
    # Built-in prefix resolvers
    # -------------------------------------------------------------------

    def _register_builtins(self) -> None:
        # No-op direct registrations; the prefix resolver handles all
        # built-ins by inspection so they pick up DB / SLM bindings
        # lazily (avoids constructing expensive singletons at boot).
        pass

    def _resolve_by_prefix(self, handle: str) -> Optional[Callable[..., Any]]:
        if not handle:
            return None
        # ``compiled_from_scans::searchable_url::<concept_id>``
        if handle.startswith("compiled_from_scans::searchable_url::"):
            return self._searchable_url_resolver(handle)
        if handle.startswith("compiled_from_scans::detected_accessor::"):
            return self._detected_accessor_resolver(handle)
        if handle.startswith("compiled_from_scans::xpath_pattern::"):
            return self._xpath_pattern_resolver(handle)
        # §8D.27 — visible agent body. Three concept-node kinds wired
        # downstream of an agent parameter card; the shape is
        # ``agent::<role>::<param_card_id>`` (see
        # ``agent_runtime.agent_handle``). Each card's ``data`` block
        # configures the step; the user can pin, edit, fork each one
        # (symmetric editing per §8D.27).
        from backend.services.agent_runtime import (
            agent_role_prefix, AGENT_ROLE_PERCEPTION,
            AGENT_ROLE_TRANSFORMER, AGENT_ROLE_EMITTER,
        )
        if handle.startswith(agent_role_prefix(AGENT_ROLE_PERCEPTION)):
            return self._agent_perception_resolver(handle)
        if handle.startswith(agent_role_prefix(AGENT_ROLE_TRANSFORMER)):
            return self._agent_transformer_resolver(handle)
        if handle.startswith(agent_role_prefix(AGENT_ROLE_EMITTER)):
            return self._agent_emitter_resolver(handle)
        # ``module::<dotted.path>`` — direct python attribute lookup.
        if handle.startswith("module::"):
            return self._module_resolver(handle[len("module::"):])
        # ``db::cypher``
        if handle == "db::cypher":
            return self._db_cypher
        if handle == "db::tfidf_retrieve":
            return self._db_tfidf_retrieve
        # ``slm::invoke``
        if handle == "slm::invoke":
            return self._slm_invoke
        # ``pretty_print::default`` — fallback for value-typed cards.
        if handle == "pretty_print::default" or handle.startswith("pretty_print::"):
            return self._pretty_print
        # User-registered extension chain. Iterated after built-ins so
        # third parties can add new backing-pointer kinds without
        # editing this file. First match wins.
        with self._lock:
            extras = list(self._extra_prefix_resolvers)
        for prefix, factory in extras:
            if handle.startswith(prefix):
                try:
                    resolved = factory(handle)
                except Exception as e:
                    logger.warning(
                        "BackingRegistry extension %r raised for %r: %s",
                        prefix, handle, e,
                    )
                    continue
                if resolved is not None:
                    return resolved
        return None

    # -------------------------------------------------------------------
    # Resolver implementations
    # -------------------------------------------------------------------

    def _searchable_url_resolver(self, handle: str):
        """Returns a callable ``(query, samples) -> [chunks]``.

        Looks up the SearchableURL concept node by the trailing id in
        the handle, reads its data block for the url + selectors, and
        invokes the scanner pipeline. The actual scan is heavy so we
        return a thin wrapper that defers the import.
        """
        cid = handle.split("::")[-1] if handle else ""

        def call(query: str = "", samples: int = 20, **_):
            try:
                from backend.services.graph_editor import get_default_graph_editor
                ge = get_default_graph_editor()
                node = ge.get_concept(cid)
                if not node or not node.data:
                    return {"ok": False, "error": f"SearchableURL {cid} not found"}
                meta = json.loads(node.data)
                # The actual scan would call into selenium_client +
                # mapper. For now we return the parameters that would
                # be passed downstream — the agent / user can wire
                # this into a real scan via routes.py /snapshot.
                return {
                    "ok": True,
                    "url": meta.get("url"),
                    "query": query,
                    "samples": int(samples),
                    "search_field_xpath": meta.get("search_field_xpath"),
                    "pagination_button_xpath": meta.get("pagination_button_xpath"),
                    "status": "ready",
                }
            except Exception as e:
                return {"ok": False, "error": str(e)}

        return call

    def _detected_accessor_resolver(self, handle: str):
        cid = handle.split("::")[-1] if handle else ""

        def call(dom_snapshot: Any = None, **_):
            try:
                from backend.services.graph_editor import get_default_graph_editor
                ge = get_default_graph_editor()
                node = ge.get_concept(cid)
                if not node or not node.data:
                    return {"ok": False, "error": f"DetectedAccessor {cid} not found"}
                meta = json.loads(node.data)
                return {
                    "ok": True,
                    "xpath": meta.get("xpath"),
                    "field_type": meta.get("field_type"),
                    "dom_present": dom_snapshot is not None,
                }
            except Exception as e:
                return {"ok": False, "error": str(e)}

        return call

    def _agent_perception_resolver(self, handle: str):
        """§8D.27 — perception node. Reads the local subgraph around
        the parameter card and returns a perception text block.

        The card's ``data`` block configures what to include:
          ``{"include_params": true, "include_apparitions": true,
             "apparition_k": 5, "include_zoi": true}``
        """
        from backend.services.agent_runtime import parse_agent_handle
        parsed = parse_agent_handle(handle)
        param_card_id = parsed[1] if parsed else ""

        def call(**_):
            try:
                from backend.services.graph_editor import get_default_graph_editor
                ge = get_default_graph_editor()
                param = ge.get_concept(param_card_id) if param_card_id else None
                if param is None:
                    return {"ok": False, "error": f"parameter card {param_card_id} not found"}
                # The perception card itself carries the config; find it.
                # By convention it is the concept node with backing_pointer
                # equal to this handle.
                cfg: Dict[str, Any] = {}
                try:
                    # Walk edges out of the param card looking for a
                    # downstream perception card.
                    for e in ge.list_concept_edges(
                        workspace_id=param.workspace_id, source_id=param_card_id, limit=20,
                    ):
                        n = ge.get_concept(e.target_id)
                        if n and n.backing_pointer == handle:
                            try:
                                cfg = json.loads(n.data) if n.data else {}
                            except Exception:
                                cfg = {}
                            break
                except Exception:
                    cfg = {}

                lines: list = []
                if cfg.get("include_params", True):
                    try:
                        params = json.loads(param.data) if param.data else {}
                    except Exception:
                        params = {"raw": param.data}
                    lines.append(f"goal: {params.get('goal', '(no goal set)')}")
                    if cfg.get("include_zoi", True) and params.get("zone_of_influence"):
                        zoi = params["zone_of_influence"]
                        top = sorted(zoi.items(), key=lambda kv: -float(kv[1]))[:5]
                        lines.append("zone_of_influence: " + ", ".join(f"{k}={v:.2f}" for k, v in top))
                if cfg.get("include_apparitions", True):
                    try:
                        from backend.services.apparition_service import ApparitionService
                        from backend.services.concept_index_service import get_concept_index_service
                        ci = get_concept_index_service(graph_editor=ge)
                        app = ApparitionService(concept_index=ci, graph_editor=ge)
                        k = int(cfg.get("apparition_k", 5))
                        cands = app.apparitions_for_subgraph_centroid(
                            param_card_id, workspace_id=param.workspace_id, k=k,
                        )
                        if cands:
                            lines.append("relevant nearby concepts:")
                            for c in cands:
                                lines.append(f"  - {c.card_id} (score {c.score:.3f})")
                    except Exception:
                        pass
                return {"ok": True, "perception": "\n".join(lines)}
            except Exception as e:
                return {"ok": False, "error": str(e)}

        return call

    def _agent_transformer_resolver(self, handle: str):
        """§8D.27 — transformer node. Calls the SLM with a prompt built
        from the card's ``data`` template + the incoming perception.

        The card's ``data`` block is the prompt template; ``{perception}``
        and ``{goal}`` are substituted before the SLM call.
        """
        from backend.services.agent_runtime import parse_agent_handle
        parsed = parse_agent_handle(handle)
        param_card_id = parsed[1] if parsed else ""

        def call(perception: str = "", goal: str = "", **_):
            try:
                from backend.services.graph_editor import get_default_graph_editor
                ge = get_default_graph_editor()
                # Find the transformer card to read its prompt template.
                template = ""
                try:
                    param = ge.get_concept(param_card_id) if param_card_id else None
                    if param is not None:
                        for e in ge.list_concept_edges(
                            workspace_id=param.workspace_id, limit=50,
                        ):
                            n = ge.get_concept(e.target_id)
                            if n and n.backing_pointer == handle:
                                template = n.data or ""
                                break
                except Exception:
                    template = ""
                if not template:
                    template = (
                        "You are a meta-cognition node in a visible concept-graph "
                        "editor. Read the perception, decide one or two useful "
                        "actions, and respond with JSON matching: "
                        '{"rationale": "...", "creates": [...], "links": [...], '
                        '"writes": [...], "deletes": [...], "self_state_updates": {}}.\n\n'
                        "Goal: {goal}\n\nPerception:\n{perception}\n\n"
                        "Respond with JSON only. Keep ``creates`` to at most 2 per tick."
                    )
                prompt = (
                    template
                    .replace("{perception}", perception or "")
                    .replace("{goal}", goal or "")
                )
                # Use the synchronous SLM path; the streaming variant
                # lives on MetaCognitionTick._call_slm_streaming.
                from backend.services.slm_client import SLMClient
                client = SLMClient()
                if hasattr(client, "chat"):
                    text = client.chat(prompt)
                else:
                    text = ""
                return {"ok": True, "text": text}
            except Exception as e:
                return {"ok": False, "error": str(e)}

        return call

    def _agent_emitter_resolver(self, handle: str):
        """§8D.27 — emitter node. Applies a JSON-shaped action envelope
        (the SLM's output) via the shared ActionResolver.

        The card's ``data`` block can carry filter config (e.g.
        ``{"allow": ["creates", "links"]}``) to disable certain action
        kinds — useful for a user-supervised mode.
        """
        from backend.services.agent_runtime import parse_agent_handle
        parsed = parse_agent_handle(handle)
        param_card_id = parsed[1] if parsed else ""

        def call(action_json: str = "", workspace_id: str = "", actor: str = "", **_):
            try:
                from backend.services.graph_editor import get_default_graph_editor
                from backend.services.agent_runtime import (
                    ActionResolver, MetaCognitionAction,
                )
                from backend.services.concept_index_service import get_concept_index_service
                ge = get_default_graph_editor()
                ci = get_concept_index_service(graph_editor=ge)
                # Read filter config from the emitter card if it exists.
                allow: Optional[set] = None
                try:
                    param = ge.get_concept(param_card_id) if param_card_id else None
                    if param is not None:
                        for e in ge.list_concept_edges(
                            workspace_id=param.workspace_id, limit=50,
                        ):
                            n = ge.get_concept(e.target_id)
                            if n and n.backing_pointer == handle:
                                try:
                                    cfg = json.loads(n.data) if n.data else {}
                                    allow_list = cfg.get("allow")
                                    if isinstance(allow_list, list):
                                        allow = set(allow_list)
                                except Exception:
                                    pass
                                break
                except Exception:
                    pass
                action = MetaCognitionAction.from_json_text(action_json)
                # Apply filter (defaults to "everything goes" if no filter).
                # ``spawns`` is the most consequential category (§8D.32.2
                # proliferation), so the filter MUST gate it alongside the
                # others — earlier revisions of this resolver missed the
                # branch and let SLM-emitted spawns slip past a tightened
                # ``allow`` list.
                if allow is not None:
                    if "creates" not in allow: action.creates.clear()
                    if "links" not in allow: action.links.clear()
                    if "writes" not in allow: action.writes.clear()
                    if "deletes" not in allow: action.deletes.clear()
                    if "invokes" not in allow: action.invokes.clear()
                    if "commits" not in allow: action.commits.clear()
                    if "reviews" not in allow: action.reviews.clear()
                    if "spawns" not in allow: action.spawns.clear()
                resolver = ActionResolver(ge, ci)
                summary = resolver.apply(
                    action, workspace_id=workspace_id or "",
                    actor_label=actor or f"agent:{param_card_id or 'anon'}",
                )
                return {"ok": True, "summary": summary, "rationale": action.rationale}
            except Exception as e:
                return {"ok": False, "error": str(e)}

        return call

    def _xpath_pattern_resolver(self, handle: str):
        cid = handle.split("::")[-1] if handle else ""

        def call(**_):
            try:
                from backend.services.graph_editor import get_default_graph_editor
                ge = get_default_graph_editor()
                node = ge.get_concept(cid)
                if not node or not node.data:
                    return {"ok": False, "error": f"XPathPattern {cid} not found"}
                return {"ok": True, "data": json.loads(node.data)}
            except Exception as e:
                return {"ok": False, "error": str(e)}

        return call

    def _module_resolver(self, dotted_path: str):
        """``module::backend.services.global_tfidf_store.get_default_store``"""
        if "." not in dotted_path:
            return None
        try:
            mod_path, attr = dotted_path.rsplit(".", 1)
            mod = importlib.import_module(mod_path)
            return getattr(mod, attr, None)
        except Exception:
            return None

    @staticmethod
    def _db_cypher(query: str = "", **_):
        from backend.database import get_connection
        from backend.services.compile_pipeline import execute_cypher
        return execute_cypher(query, db_conn=get_connection())

    @staticmethod
    def _db_tfidf_retrieve(query: str = "", k: int = 10, **_):
        try:
            from backend.services.global_tfidf_store import get_default_store
            store = get_default_store()
            if hasattr(store, "search"):
                results = store.search(query, k=int(k))
                return {"ok": True, "results": results}
            return {"ok": False, "error": "store has no search method"}
        except Exception as e:
            return {"ok": False, "error": str(e)}

    @staticmethod
    def _slm_invoke(meta_prompt: str = "", prompt: str = "", **_):
        try:
            from backend.services.slm_client import SLMClient
            client = SLMClient()
            full = (meta_prompt + "\n\n" + prompt) if meta_prompt else prompt
            # Sync wrapper. The async streaming path is in agent_runtime.
            if hasattr(client, "chat"):
                return {"ok": True, "text": client.chat(full)}
            return {"ok": False, "error": "SLM client has no sync chat method"}
        except Exception as e:
            return {"ok": False, "error": str(e)}

    @staticmethod
    def _pretty_print(value: Any = None, **_):
        try:
            return {"ok": True, "text": json.dumps(value, indent=2, default=str)}
        except Exception as e:
            return {"ok": False, "error": str(e), "text": str(value)}


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------

_REG: Optional[BackingRegistry] = None
_REG_LOCK = threading.Lock()


def get_backing_registry() -> BackingRegistry:
    global _REG
    with _REG_LOCK:
        if _REG is None:
            _REG = BackingRegistry()
    return _REG
